In [ ]:
import pandas as pd

train_df = pd.DataFrame([
                         [0,0,0],
                         [0,1,1],
                         [1,0,1],
                         [1,1,2],
                         [2,0,2],
                         [2,1,3],
                         [3,0,3],
                         [3,1,4],
                         [4,0,4],
                         [4,1,5]
])
train_df

0  1  2
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  2
4  2  0  2
5  2  1  3
6  3  0  3
7  3  1  4
8  4  0  4
9  4  1  5

In [ ]:
x_train = train_df.iloc[:,0:2]
y_train = train_df.iloc[:,2]

In [ ]:
test_df = pd.DataFrame([
                        [0,3,3],
                         [1,3,4],
                         [2,3,5],
                         [3,2,5],
                         [0,4,4]
])

x_test = test_df.iloc[:,0:2]
y_test = test_df.iloc[:,2]

In [ ]:
# Training Data : Input and Output will be used to find a pattern
# Testing Data : We will use only Input and get the predicted output
# Match the predicted output with the real output

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras
tf.__version__

'2.3.0'

In [ ]:
# Points to remember 
1. We never write the input layer as a first layer
2. 

SyntaxError: ignored

In [ ]:
# Neural Network Architecture
# How many units of Neurons?
# Which is the Activation Function?
# 1. Input Layer - 
# 2. Hidden Layer - 3 Neurons, Activation = 'Relu'
# 3. Output Layer - 1 Neuron, Activation = 'Linear' 

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = tf.keras.Sequential()
model.add(Dense(3,activation = 'relu',input_dim = 2))
model.add(Dense(1,activation = 'linear'))


In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 4         
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mae',optimizer='adam')

In [ ]:
model.get_weights()

[array([[-0.30939746, -0.38836747, -1.030407  ],
        [-0.82305765, -0.7851017 ,  1.0696898 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.41428214],
        [ 0.41109145],
        [ 0.10230315]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.fit(x_train,y_train,epochs = 800)

Epoch 1/800
1/1 [==============================] - 0s 1ms/step - loss: 2.4887
Epoch 2/800
1/1 [==============================] - 0s 3ms/step - loss: 2.4877
Epoch 3/800
1/1 [==============================] - 0s 1ms/step - loss: 2.4868
Epoch 4/800
1/1 [==============================] - 0s 1ms/step - loss: 2.4858
Epoch 5/800
1/1 [==============================] - 0s 1ms/step - loss: 2.4849
Epoch 6/800
1/1 [==============================] - 0s 1ms/step - loss: 2.4839
Epoch 7/800
1/1 [==============================] - 0s 2ms/step - loss: 2.4830
Epoch 8/800
1/1 [==============================] - 0s 2ms/step - loss: 2.4820
Epoch 9/800
1/1 [==============================] - 0s 2ms/step - loss: 2.4811
Epoch 10/800
1/1 [==============================] - 0s 2ms/step - loss: 2.4801
Epoch 11/800
1/1 [==============================] - 0s 2ms/step - loss: 2.4791
Epoch 12/800
1/1 [==============================] - 0s 2ms/step - loss: 2.4782
Epoch 13/800
1/1 [==============================] - 0s 2ms/st

In [ ]:
model.get_weights()

[array([[ 0.5130643 , -0.11564595,  1.1697518 ],
        [-0.44873524, -0.14863908,  0.91141367]], dtype=float32),
 array([0.35085806, 0.        , 0.29000896], dtype=float32),
 array([[ 0.25146735],
        [-0.5254023 ],
        [ 0.6325648 ]], dtype=float32),
 array([0.25245008], dtype=float32)]

In [ ]:
import numpy as np

model.predict(x_test)

array([[0.61718786],
       [0.589762  ],
       [0.5623362 ],
       [0.6850381 ],
       [0.4670601 ]], dtype=float32)

In [ ]:
y_test

0    3
1    4
2    5
3    5
4    4
Name: 2, dtype: int64